import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
    BACKGROUND_COLOR,
    PRIMARY_COLOR,
    PRIMARY_TEXT_COLOR,
} from '../../../themes/colors';

const {width} = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#272E3F',
    },
    wrapper: {
        flex: 1,
        backgroundColor: BACKGROUND_COLOR,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
        marginTop: Platform.OS == 'ios' ? 45 : 5,
    },
    title: {
        fontSize: 28,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    topBar: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 20,
        paddingHorizontal: 25,
    },
    header: {
        paddingHorizontal: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 100,
        backgroundColor: PRIMARY_TEXT_COLOR,
        alignSelf: 'center',
    },
    name: {
        fontSize: 12,
        color: '#88919E',
        fontFamily: 'Rubik-Medium',
        textAlign: 'left',
        alignSelf: 'flex-start',
        marginBottom: 15,
    },
    section: {
        borderTopColor: '#E5E5E5',
        borderTopWidth: 1,
        paddingLeft: 25,
        paddingTop: 8,
    },
    sectionName: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'left',
        paddingHorizontal: 25,
        marginTop: 25,
        marginBottom: 15,
    },
    sectionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomColor: '#E5E5E5',
        borderBottomWidth: 1,
        justifyContent: 'space-between',
        paddingRight: 10,
    },
    sectionItemLabel: {
        fontSize: 14,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        paddingVertical: 15,
    },
    version: {
        color: '#88919E',
        fontSize: 12,
        fontFamily: 'Rubik-Regular',
        textAlign: 'center',
        marginTop: 50,
        marginBottom: 10,
    },
    sectionRightLabel: {
        fontSize: 14,
        color: '#8F8F8F',
        fontFamily: 'Rubik-Regular',
    },
    sectionRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    touchImage: {
        width: 40,
        height: 40,
        borderRadius: 50,
        overflow: 'hidden',
        backgroundColor: PRIMARY_COLOR,
        marginVertical: 10,
    },
    sectionImage: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
        overflow: 'hidden',
    },
    button: {
        borderRadius: 10,
        paddingVertical: 15,
        paddingHorizontal: 20,
        alignSelf: 'center',
        marginBottom: 20,
        minWidth: 250,
    },
    btnLabel: {
        fontSize: 14,
        color: 'white',
        fontFamily: 'Rubik-Medium',
        letterSpacing: 2,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    textInput: {
        fontSize: 16,
        color: 'black',
        fontFamily: 'Rubik-Regular',
        paddingVertical: 15,
        flex: 1,
        marginLeft: 15,
    },
    circleview: {
        width: 15,
        height: 15,
        borderRadius: 15,
        marginRight: 10,
    },
    chartbar: {
        height: 25,
        borderRadius: 5,
    },
    sectionTotalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderTopColor: PRIMARY_COLOR,
        borderTopWidth: 1,
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        paddingLeft: 25,
    },
    inputContainer: {
        width: width - 40,
        backgroundColor: 'rgba(142, 142, 147, 0.12)',
        borderRadius: 50,
        paddingVertical: Platform.OS == 'ios' ? 5 : 0,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        alignSelf: 'center',
    },
    inputIcon: {
        marginRight: 5,
        width: 20,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        paddingVertical: 5,
    },
    amountTitle: {
        fontSize: 28,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    planHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 10,
    },
    chipgroup: {
        marginTop: 10,
        flexDirection: 'row',
        marginHorizontal: 20,
        marginBottom: 5,
        flexWrap: 'wrap',
    },
    chip: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderWidth: 1,
        borderRadius: 5,
        marginRight: 10,
        marginVertical: 5,
    },
    chiplabel: {
        fontSize: 12,
        fontFamily: 'Rubik-Regular',
    },
    member: {
        borderBottomColor: '#E5E5E5',
        borderBottomWidth: 1,
        paddingVertical: 5,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: 20,
        marginBottom: 10,
    },
    memberAvatar: {
        width: 35,
        height: 35,
        borderRadius: 35,
        backgroundColor: PRIMARY_TEXT_COLOR,
        marginRight: 10,
        overflow: 'hidden',
    },
    avatarimg: {
        width: 35,
        height: 35,
        resizeMode: 'cover',
    },
    memberName: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    memberDescp: {
        fontSize: 14,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
    },
    memberLabel: {
        fontSize: 20,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'left',
        marginLeft: 20,
    },
    memberamount: {
        fontSize: 16,
        fontFamily: 'Rubik-Medium',
    },
    modal: {
        justifyContent: 'center',
        margin: 20,
    },
    modalContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderRadius: 20,
        paddingTop: 20,
    },
    modalcloseBtn: {
        backgroundColor: '#2F425D',
        opacity: 0.2,
        width: 70,
        height: Platform.OS == 'android' ? 0 : 5,
        borderRadius: 5,
        alignSelf: 'center',
        marginVertical: Platform.OS == 'android' ? 20 : 40,
    },
    confirmBtn: {
        borderRadius: 10,
        paddingVertical: 15,
        width: '100%',
        marginVertical: 20,
        marginBottom: 30,
        backgroundColor: PRIMARY_COLOR,
    },
    confirmBtnLabel: {
        color: 'white',
        fontSize: 14,
        alignSelf: 'center',
        fontFamily: 'Rubik-Medium',
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    invoiceItem: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 15,
        marginVertical: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginHorizontal: 20,
        paddingVertical: 30,
    },
    invoiceItemHeader: {
        justifyContent: 'space-between',
        flexDirection: 'row',
    },
    invoicetitle: {
        fontSize: 20,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        fontWeight: 'bold',
        letterSpacing: 1.5,
        lineHeight: 20,
    },
    invoiceamount: {
        fontSize: 20,
        color: PRIMARY_COLOR,
        fontFamily: 'Rubik-Medium',
        lineHeight: 20,
    },
    invoiceItemContent: {
        marginTop: 10,
    },
    invoiceContentText: {
        fontSize: 16,
        color: '#88919e',
        fontFamily: 'Rubik-Medium',
    },
    invoiceContentValue: {
        fontSize: 16,
        color: '#88919e',
        fontFamily: 'Rubik-Regular',
    },
    invoiceItemFooter: {
        flexDirection: 'row',
        marginTop: 20,
    },
    iconContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    iconlabel: {
        fontSize: 12,
        color: '#88919E',
        fontFamily: 'Rubik-Medium',
        lineHeight: 20,
    },
    barprogress: {
        borderRadius: 3,
        backgroundColor: 'transparent',
        flex: 1,
        flexDirection: 'row',
        overflow: 'hidden',
        marginBottom: 10,
    },
    barBlock: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    circleColor: {
        width: 20,
        height: 20,
        borderRadius: 20,
        overflow: 'hidden',
        marginRight: 10,
    },
    invoicecard_chartItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 5,
    },
    invoicecard_chartlabel: {
        fontSize: 12,
        color: '#2F425D',
        fontFamily: 'Rubik-Medium',
    },
    error: {
        color: 'red',
        fontSize: 10,
        fontFamily: 'Rubik-Regular',
        paddingBottom: 5,
        marginLeft: 15,
    },
    pickerLabel: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'center',
    },
});
