import {StyleSheet, Platform} from 'react-native';
import {
    BACKGROUND_COLOR,
    PRIMARY_COLOR,
    PRIMARY_TEXT_COLOR,
} from '../../../themes/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#272E3F',
    },
    wrapper: {
        flex: 1,
        backgroundColor: BACKGROUND_COLOR,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
        marginTop: Platform.OS == 'ios' ? 45 : 5,
    },
    title: {
        fontSize: 28,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    topBar: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 20,
        paddingHorizontal: 25,
    },
    header: {
        paddingHorizontal: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 100,
        backgroundColor: PRIMARY_TEXT_COLOR,
        alignSelf: 'center',
    },
    name: {
        fontSize: 12,
        color: '#88919E',
        fontFamily: 'Rubik-Medium',
        textAlign: 'left',
        alignSelf: 'flex-start',
        marginBottom: 15,
    },
    section: {
        borderTopColor: '#E5E5E5',
        borderTopWidth: 1,
        paddingLeft: 25,
        paddingVertical: 8,
    },
    sectionName: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'left',
        paddingHorizontal: 25,
        marginTop: 25,
        marginBottom: 15,
    },
    sectionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomColor: '#E5E5E5',
        borderBottomWidth: 1,
        justifyContent: 'space-between',
        paddingRight: 10,
    },
    sectionItemLabel: {
        fontSize: 14,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        paddingVertical: 15,
    },
    version: {
        color: '#88919E',
        fontSize: 12,
        fontFamily: 'Rubik-Regular',
        textAlign: 'center',
        marginTop: 50,
        marginBottom: 10,
    },
    sectionRightLabel: {
        fontSize: 14,
        color: '#8F8F8F',
        fontFamily: 'Rubik-Regular',
    },
    sectionRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    touchImage: {
        width: 40,
        height: 40,
        borderRadius: 50,
        overflow: 'hidden',
        backgroundColor: PRIMARY_COLOR,
        marginVertical: 10,
    },
    sectionImage: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
        overflow: 'hidden',
    },
    button: {
        borderRadius: 10,
        paddingVertical: 15,
        paddingHorizontal: 20,
        alignSelf: 'center',
        minWidth: 150,
        backgroundColor: PRIMARY_COLOR,
    },
    btnLabel: {
        fontSize: 14,
        color: 'white',
        fontFamily: 'Rubik-Medium',
        letterSpacing: 2,
        textAlign: 'center',
    },
    textInput: {
        fontSize: 16,
        color: 'black',
        fontFamily: 'Rubik-Regular',
        paddingVertical: 15,
        flex: 1,
        marginLeft: 15,
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    maincontent: {
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 25,
        alignSelf: 'center',
    },
    togglebtngroup: {
        flexDirection: 'row',
        width: '80%',
        backgroundColor: PRIMARY_COLOR,
        borderColor: PRIMARY_COLOR,
        borderWidth: 2,
        borderRadius: 5,
    },
    togglebtn: {
        flex: 0.5,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 10,
    },
    togglebtnlabel: {
        fontSize: 12,
        color: PRIMARY_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'center',
    },
    contbItem: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 15,
        marginVertical: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    contbContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    avatarimg: {
        width: 35,
        height: 35,
        resizeMode: 'cover',
    },
    contbItemName: {
        fontSize: 12,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        fontWeight: 'bold',
        letterSpacing: 1.5,
        lineHeight: 20,
    },
    contbItemDesp: {
        fontSize: 16,
        color: '#6C8AF1',
        fontFamily: 'Rubik-Medium',
        lineHeight: 20,
    },
    contbItemStatus: {
        fontSize: 12,
        color: '#3AF1AF',
        fontFamily: 'Rubik-Medium',
        lineHeight: 20,
    },
});
