import {StyleSheet, Platform} from 'react-native';
import {
    BACKGROUND_COLOR,
    PRIMARY_COLOR,
    PRIMARY_TEXT_COLOR,
} from '../../themes/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BACKGROUND_COLOR,
    },
    scene: {
        flexGrow: 1,
        backgroundColor: BACKGROUND_COLOR,
    },
    sceneTitle: {
        fontSize: 18,
        fontFamily: 'Rubik-Medium',
        color: PRIMARY_TEXT_COLOR,
        marginLeft: 25,
        marginBottom: 15,
    },
    sceneFields: {
        borderTopColor: '#C8C7CC',
        borderTopWidth: 0.5,
        borderBottomColor: '#C8C7CC',
        borderBottomWidth: 0.5,
        paddingHorizontal: 25,
    },
    tabBar: {
        paddingTop: Platform.OS == 'ios' ? 40 : 20,
        paddingHorizontal: 25,
        width: '100%',
        backgroundColor: BACKGROUND_COLOR,
    },
    tabItem: {
        alignItems: 'center',
        padding: 16,
    },
    tabTitle: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'left',
        lineHeight: 19,
    },
    tabPage: {
        fontSize: 12,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        lineHeight: 16,
        textAlign: 'left',
    },
    nextBtn: {
        paddingHorizontal: 5,
        paddingBottom: 10,
    },
    nextBtnLabel: {
        fontSize: 20,
        color: PRIMARY_COLOR,
        fontFamily: 'Rubik-Medium',
        lineHeight: 22,
        textAlign: 'right',
    },
    paginationDot: {
        width: 40,
        height: 8,
        borderRadius: 10,
        marginRight: 8,
        marginTop: 10,
        marginBottom: 25,
    },
    txtInput: {
        backgroundColor: BACKGROUND_COLOR,
        borderRadius: 12,
        marginTop: 50,
        textAlign: 'center',
        fontFamily: 'Rubik-Medium',
        color: PRIMARY_TEXT_COLOR,
        ...(Platform.OS == 'ios'
            ? {
                  paddingVertical: 10,
              }
            : {}),
    },
    title: {
        fontSize: 25,
        fontFamily: 'Rubik-Medium',
        color: 'white',
        alignSelf: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    description: {
        fontSize: 15,
        fontFamily: 'Rubik-Regular',
        color: 'white',
        textAlign: 'center',
        alignSelf: 'center',
        width: 250,
        lineHeight: 19,
    },
    avatar: {
        width: 100,
        height: 100,
        backgroundColor: BACKGROUND_COLOR,
        alignSelf: 'center',
        borderRadius: 100,
        marginTop: 30,
        overflow: 'hidden',
    },
    clubImage: {
        width: 100,
        height: 100,
        resizeMode: 'cover',
    },
    chooseBtn: {
        borderWidth: 2,
        borderColor: PRIMARY_COLOR,
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 10,
        alignSelf: 'center',
        backgroundColor: 'white',
        marginVertical: 20,
    },
    chooseBtnLabel: {
        fontSize: 14,
        fontFamily: 'Rubik-Medium',
        color: PRIMARY_COLOR,
        letterSpacing: 2,
        textTransform: 'uppercase',
        alignSelf: 'center',
    },
    colorText: {
        fontSize: 10,
        fontFamily: 'Rubik-Medium',
        color: 'white',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
        alignSelf: 'center',
    },
    colorPanel: {
        backgroundColor: BACKGROUND_COLOR,
        borderRadius: 16,
        padding: 20,
        alignSelf: 'center',
        marginTop: 10,
    },
    colorItem: {
        width: 35,
        height: 35,
        borderRadius: 32,
        margin: 8,
        borderWidth: 3,
        borderColor: 'transparent',
    },
    spinnerTextStyle: {
        fontSize: 14,
        fontFamily: 'Rubik-Medium',
        color: 'white',
        letterSpacing: 1.5,
    },
    inputContainer: {
        width: '100%',
        paddingVertical: Platform.OS == 'ios' ? 10 : 0,
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
        backgroundColor: BACKGROUND_COLOR,
        borderRadius: 12,
        marginVertical: 5,
    },
    inputIcon: {
        marginRight: 10,
        width: 20,
        color: PRIMARY_TEXT_COLOR,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    termscontainer: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: BACKGROUND_COLOR,
        paddingTop: 50,
    },
    termsDescriotion: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        marginBottom: 30,
        textAlign: 'center',
    },
    termsItem: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: 8,
        backgroundColor: 'white',
        paddingVertical: 10,
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginVertical: 10,
    },
    termsItemTitle: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        lineHeight: 30,
    },
    termsItemSubTitle: {
        fontSize: 14,
        color: '#6C8AF1',
        fontFamily: 'Rubik-Regular',
    },
    confirmBtn: {
        position: 'absolute',
        bottom: 20,
        borderRadius: 10,
        paddingVertical: 15,
        width: '100%',
        marginVertical: 20,
        backgroundColor: PRIMARY_COLOR,
    },
    confirmBtnLabel: {
        color: 'white',
        fontSize: 14,
        alignSelf: 'center',
        fontFamily: 'Rubik-Medium',
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    signuptitle: {
        fontSize: 28,
        color: PRIMARY_COLOR,
        fontFamily: 'Rubik-Medium',
        alignSelf: 'center',
        marginBottom: 20,
    },
    backButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        flexDirection: 'row',
    },
    multiSelectContainer: {
        marginBottom: 5,
        backgroundColor: BACKGROUND_COLOR,
        borderRadius: 12,
        marginVertical: 5,
        paddingHorizontal: 10,
    },
    styleTextDropdown: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    styleInputGroup: {
        backgroundColor: BACKGROUND_COLOR,
    },
    styleListContainer: {
        backgroundColor: BACKGROUND_COLOR,
    },
    styleDropdownMenu: {
        ...(Platform.OS == 'ios'
            ? {
                  paddingVertical: 10,
              }
            : {}),
    },
    categoryTextContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
});
