import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
    BACKGROUND_COLOR,
    PRIMARY_COLOR,
    PRIMARY_TEXT_COLOR,
} from '../../themes/colors';

const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
    modal: {
        justifyContent: Platform.OS == 'android' ? 'center' : 'flex-end',
        margin: Platform.OS == 'android' ? 20 : 0,
    },
    modalContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: Platform.OS == 'android' ? 20 : 0,
        borderBottomRightRadius: Platform.OS == 'android' ? 20 : 0,
    },
    modalcloseBtn: {
        backgroundColor: '#2F425D',
        opacity: 0.2,
        width: 70,
        height: Platform.OS == 'android' ? 0 : 5,
        borderRadius: 5,
        alignSelf: 'center',
        marginVertical: Platform.OS == 'android' ? 20 : 40,
    },
    container: {
        flexGrow: 1,
        paddingHorizontal: 30,
        paddingTop: 200,
        backgroundColor: BACKGROUND_COLOR,
    },
    backButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        flexDirection: 'row',
    },
    title: {
        fontSize: 20,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'center',
        marginBottom: 20,
    },
    socialBtn: {
        borderRadius: 4,
        paddingVertical: 15,
        width: '100%',
        marginVertical: 5,
    },
    socialBtnLabel: {
        color: 'white',
        fontSize: 14,
        alignSelf: 'center',
    },
    dividerContainer: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    divider: {
        flex: 1,
        height: 1,
        backgroundColor: 'rgba(196, 196, 196, 0.5)',
    },
    order: {
        fontSize: 12,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        textAlign: 'center',
        marginHorizontal: 20,
        marginVertical: 20,
    },
    ghostBtn: {
        paddingVertical: 10,
        paddingHorizontal: 20,
    },
    emailSignup: {
        fontSize: 14,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        textAlign: 'center',
    },
    haveaccountContainer: {
        paddingVertical: 20,
        paddingHorizontal: 40,
        marginBottom: 20,
    },
    haveaccount: {
        fontSize: 14,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        textAlign: 'center',
    },
    Anmelden: {
        fontSize: 14,
        color: PRIMARY_COLOR,
        fontFamily: 'Rubik-Medium',
    },
    //signup
    signuptitle: {
        fontSize: 28,
        color: PRIMARY_COLOR,
        fontFamily: 'Rubik-Medium',
        alignSelf: 'flex-start',
        marginBottom: 20,
    },
    registerBtn: {
        borderRadius: 10,
        paddingVertical: 15,
        width: '100%',
        marginVertical: 20,
        marginBottom: 40,
        backgroundColor: PRIMARY_COLOR,
    },
    registerBtnLabel: {
        color: 'white',
        fontSize: 14,
        alignSelf: 'center',
        fontFamily: 'Rubik-Medium',
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    inputContainer: {
        width: '100%',
        borderBottomColor: '#C4C4C4',
        borderBottomWidth: 1,
        paddingVertical: Platform.OS == 'ios' ? 10 : 0,
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
    },
    inputIcon: {
        marginRight: 10,
        width: 20,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
    },
    //Login
    forgotBtn: {
        marginVertical: 10,
        marginBottom: 30,
    },
    forgotLabel: {
        fontSize: 12,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Medium',
        alignSelf: 'center',
    },
    //terms
    termscontainer: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: BACKGROUND_COLOR,
        paddingTop: 50,
    },
    termsDescriotion: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        marginBottom: 30,
    },
    termsItem: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: 8,
        backgroundColor: 'white',
        paddingVertical: 10,
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginVertical: 10,
    },
    termsItemTitle: {
        fontSize: 16,
        color: PRIMARY_TEXT_COLOR,
        fontFamily: 'Rubik-Regular',
        lineHeight: 30,
    },
    termsItemSubTitle: {
        fontSize: 14,
        color: '#6C8AF1',
        fontFamily: 'Rubik-Regular',
    },
    confirmBtn: {
        position: 'absolute',
        bottom: 20,
        borderRadius: 10,
        paddingVertical: 15,
        width: '100%',
        marginVertical: 20,
        backgroundColor: PRIMARY_COLOR,
    },
    confirmBtnLabel: {
        color: 'white',
        fontSize: 14,
        alignSelf: 'center',
        fontFamily: 'Rubik-Medium',
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
});
